apiVersion: v1
kind: Service
metadata:
  labels:
    app: core
  name: core
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "5000"
    port: 5000
    targetPort: 5000
  - name: "5001"
    port: 5001
    targetPort: 5001
  - name: "5050"
    port: 5050
    targetPort: 5050
  - name: "5051"
    port: 5051
    targetPort: 5051
  - name: "5052"
    port: 5052
    targetPort: 5052
  selector:
    app: core
