version: '3.3'

services:
  dhis-postgres:
    container_name: dhis-postgres
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: dhis2
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
    volumes:
      - hmis-db-data:/var/lib/postgresql/data

  dhis-web:
    container_name: dhis-web
    image: dhis2/core:2.35.3
    volumes:
      - hmis-app-data:/DHIS2_home
    environment:
      - WAIT_FOR_DB_CONTAINER=dhis-postgres:5432 -t 0
    ports:
      - "8081:8080"
    depends_on:
      - dhis-postgres

volumes:
  hmis-app-data:
    external: true
  hmis-db-data:
