version: '3.3'

services:
  # container for executing config import scripts for setting up initial config
  core-config-importer:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-1"
      replicas: 1
