version: "3.3"

services:
  openfn:
    environment:
      PROJECT_DIR: /opt/app/project
      # MIX_ENV: prod
    volumes:
      - microservice_him_hapi:/opt/app/project

volumes:
  microservice_him_hapi:
    external: true

networks:
  default:
    external:
      name: instant_default