apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f packages/data-analytics/docker/docker-compose.elastic.yml -o packages/data-analytics/kubernetes/main/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: es-analytics
  name: es-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es-analytics
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f packages/data-analytics/docker/docker-compose.elastic.yml -o packages/data-analytics/kubernetes/main/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: es-analytics
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
            - name: node.name
              value: es01
            - name: xpack.security.enabled
              value: "true"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
          name: es-analytics
          ports:
            - containerPort: 9200
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      restartPolicy: Always
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data
status: {}
