// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: indexjson.proto

package fhirnpmproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexJson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexVersion int32              `protobuf:"varint,1,opt,name=index_version,json=index-version,proto3" json:"index_version,omitempty"`
	Filesrep     []*IndexJson_Files `protobuf:"bytes,100,rep,name=filesrep,json=files,proto3" json:"filesrep,omitempty"`
}

func (x *IndexJson) Reset() {
	*x = IndexJson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_indexjson_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexJson) ProtoMessage() {}

func (x *IndexJson) ProtoReflect() protoreflect.Message {
	mi := &file_indexjson_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexJson.ProtoReflect.Descriptor instead.
func (*IndexJson) Descriptor() ([]byte, []int) {
	return file_indexjson_proto_rawDescGZIP(), []int{0}
}

func (x *IndexJson) GetIndexVersion() int32 {
	if x != nil {
		return x.IndexVersion
	}
	return 0
}

func (x *IndexJson) GetFilesrep() []*IndexJson_Files {
	if x != nil {
		return x.Filesrep
	}
	return nil
}

type IndexJson_Files struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename     string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ResourceType string `protobuf:"bytes,4,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	Id           string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Url          string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Version      string `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Kind         string `protobuf:"bytes,8,opt,name=kind,proto3" json:"kind,omitempty"`
	Type         string `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *IndexJson_Files) Reset() {
	*x = IndexJson_Files{}
	if protoimpl.UnsafeEnabled {
		mi := &file_indexjson_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexJson_Files) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexJson_Files) ProtoMessage() {}

func (x *IndexJson_Files) ProtoReflect() protoreflect.Message {
	mi := &file_indexjson_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexJson_Files.ProtoReflect.Descriptor instead.
func (*IndexJson_Files) Descriptor() ([]byte, []int) {
	return file_indexjson_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IndexJson_Files) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *IndexJson_Files) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *IndexJson_Files) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IndexJson_Files) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IndexJson_Files) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IndexJson_Files) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *IndexJson_Files) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_indexjson_proto protoreflect.FileDescriptor

var file_indexjson_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x66, 0x68, 0x69, 0x72, 0x6e, 0x70, 0x6d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x97, 0x02, 0x0a, 0x09, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x24, 0x0a,
	0x0d, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2d, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x72, 0x65, 0x70, 0x18,
	0x64, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x68, 0x69, 0x72, 0x6e, 0x70, 0x6d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4a, 0x73, 0x6f, 0x6e, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0xab, 0x01, 0x0a, 0x05,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x69, 0x65, 0x2f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2f, 0x67, 0x6f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x2f, 0x66, 0x68, 0x69, 0x72, 0x6e, 0x70, 0x6d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_indexjson_proto_rawDescOnce sync.Once
	file_indexjson_proto_rawDescData = file_indexjson_proto_rawDesc
)

func file_indexjson_proto_rawDescGZIP() []byte {
	file_indexjson_proto_rawDescOnce.Do(func() {
		file_indexjson_proto_rawDescData = protoimpl.X.CompressGZIP(file_indexjson_proto_rawDescData)
	})
	return file_indexjson_proto_rawDescData
}

var file_indexjson_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_indexjson_proto_goTypes = []interface{}{
	(*IndexJson)(nil),       // 0: fhirnpmproto.IndexJson
	(*IndexJson_Files)(nil), // 1: fhirnpmproto.IndexJson.Files
}
var file_indexjson_proto_depIdxs = []int32{
	1, // 0: fhirnpmproto.IndexJson.filesrep:type_name -> fhirnpmproto.IndexJson.Files
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_indexjson_proto_init() }
func file_indexjson_proto_init() {
	if File_indexjson_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_indexjson_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexJson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_indexjson_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexJson_Files); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_indexjson_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_indexjson_proto_goTypes,
		DependencyIndexes: file_indexjson_proto_depIdxs,
		MessageInfos:      file_indexjson_proto_msgTypes,
	}.Build()
	File_indexjson_proto = out.File
	file_indexjson_proto_rawDesc = nil
	file_indexjson_proto_goTypes = nil
	file_indexjson_proto_depIdxs = nil
}
